import React from 'react';
import { Shield, Zap, Sparkles } from 'lucide-react';
import type { RouteMeta } from '../../types/routing';

export const TECHNIQUE_PANEL_COMPONENTS: Record<string, React.ComponentType<any>> = {
    'cross-examination': React.lazy(() => import('./CrossExaminationPanel')),
    'delta-focusing': React.lazy(() => import('./DeltaFocusingPanel')),
    'vulnerability-targeting': React.lazy(() => import('./VulnerabilityTargetingPanel')),
    'agreement-anchoring': React.lazy(() => import('./AgreementAnchoringPanel')),
    'graph-minimax': React.lazy(() => import('./GraphMinimaxPanel')),
    'burden-of-proof': React.lazy(() => import('./BurdenOfProofPanel')),
    'consistency-check': React.lazy(() => import('./ConsistencyCheckPanel')),
    'credibility-scoring': React.lazy(() => import('./CredibilityScoringPanel')),
    'causal-graph': React.lazy(() => import('./CausalGraphPanel')),
    'pre-publish-critic': React.lazy(() => import('./PrePublishCriticPanel')),
    'fact-checking': React.lazy(() => import('./FactCheckingPanel')),
    'epistemic-calibration': React.lazy(() => import('./EpistemicCalibrationPanel')),
    'socratic-pivot': React.lazy(() => import('./SocraticPivotPanel')),
    'concession-engine': React.lazy(() => import('./ConcessionEnginePanel')),
    'bayesian-judges': React.lazy(() => import('./BayesianJudgesPanel')),
    'dpo-sampler': React.lazy(() => import('./DpoSamplerPanel')),
    'critic': React.lazy(() => import('./CriticPanel')),
    'pivot': React.lazy(() => import('./PivotPanel')),
    'concession': React.lazy(() => import('./ConcessionPanel')),
    'triangulation': React.lazy(() => import('./TriangulationPanel')),
    'empathy': React.lazy(() => import('./EmpathyPanel')),
    'heat': React.lazy(() => import('./HeatPanel')),
    'sentinel': React.lazy(() => import('./SentinelPanel')),
    'redundancy': React.lazy(() => import('./RedundancyPanel')),
    'replay': React.lazy(() => import('./ReplayPanel')),
    'enthymeme': React.lazy(() => import('./EnthymemePanel')),
    'multi-hop': React.lazy(() => import('./MultiHopPanel')),
    'bias-exploit': React.lazy(() => import('./BiasExploitPanel')),
    'interrupt': React.lazy(() => import('./InterruptPanel')),
    'frame': React.lazy(() => import('./FramePanel')),
    'rhetorical-device': React.lazy(() => import('./RhetoricalDevicePanel')),
    'narrative-arc': React.lazy(() => import('./NarrativeArcPanel')),
    'abstraction-ladder': React.lazy(() => import('./AbstractionLadderPanel')),
    'role-reversal': React.lazy(() => import('./RoleReversalPanel')),
    'fog-of-war': React.lazy(() => import('./FogOfWarPanel')),
    'evidence-revelation': React.lazy(() => import('./EvidenceRevelationPanel')),
    'humor': React.lazy(() => import('./HumorPanel')),
    'status-dynamics': React.lazy(() => import('./StatusDynamicsPanel')),
    'style-matching': React.lazy(() => import('./StyleMatchingPanel')),
    'dynamic-persona': React.lazy(() => import('./DynamicPersonaPanel')),
    'strategist': React.lazy(() => import('./StrategistPanel')),
    'whisper-channels': React.lazy(() => import('./WhisperChannelsPanel')),
    'alliance': React.lazy(() => import('./AlliancePanel')),
    'prediction-market': React.lazy(() => import('./PredictionMarketPanel')),
    'rtom': React.lazy(() => import('./RtomPanel')),
    'strategy-fingerprint': React.lazy(() => import('./StrategyFingerprintPanel')),
    'objection-anticipation': React.lazy(() => import('./ObjectionAnticipationPanel')),
    'evidence-triangulation': React.lazy(() => import('./EvidenceTriangulationPanel')),
    'hegelian-synthesis': React.lazy(() => import('./HegelianSynthesisPanel')),
    'uncertainty-propagation': React.lazy(() => import('./UncertaintyPropagationPanel')),
    'rhetoric-safety': React.lazy(() => import('./RhetoricSafetyPanel')),
    'blind-evaluation': React.lazy(() => import('./BlindEvaluationPanel')),
    'bidding-time': React.lazy(() => import('./BiddingTimePanel')),
    'adaptive-order': React.lazy(() => import('./AdaptiveOrderPanel')),
    'executable-evidence': React.lazy(() => import('./ExecutableEvidencePanel')),
    'hidden-incentives': React.lazy(() => import('./HiddenIncentivesPanel')),
    'semantic-blending': React.lazy(() => import('./SemanticBlendingPanel')),
    'judge-deliberation': React.lazy(() => import('./JudgeDeliberationPanel')),
};

export const TECHNIQUE_NAV_ITEMS: RouteMeta[] = [
    { id: 'cross-examination', labelKey: 'nav.cross-examination', icon: React.createElement(Shield), color: '#8b5cf6', lazy: true },
    { id: 'delta-focusing', labelKey: 'nav.delta-focusing', icon: React.createElement(Shield), color: '#8b5cf6', lazy: true },
    { id: 'vulnerability-targeting', labelKey: 'nav.vulnerability-targeting', icon: React.createElement(Shield), color: '#8b5cf6', lazy: true },
    { id: 'agreement-anchoring', labelKey: 'nav.agreement-anchoring', icon: React.createElement(Shield), color: '#8b5cf6', lazy: true },
    { id: 'graph-minimax', labelKey: 'nav.graph-minimax', icon: React.createElement(Shield), color: '#8b5cf6', lazy: true },
    { id: 'burden-of-proof', labelKey: 'nav.burden-of-proof', icon: React.createElement(Shield), color: '#8b5cf6', lazy: true },
    { id: 'consistency-check', labelKey: 'nav.consistency-check', icon: React.createElement(Shield), color: '#8b5cf6', lazy: true },
    { id: 'credibility-scoring', labelKey: 'nav.credibility-scoring', icon: React.createElement(Shield), color: '#8b5cf6', lazy: true },
    { id: 'causal-graph', labelKey: 'nav.causal-graph', icon: React.createElement(Shield), color: '#8b5cf6', lazy: true },
    { id: 'pre-publish-critic', labelKey: 'nav.pre-publish-critic', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'fact-checking', labelKey: 'nav.fact-checking', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'epistemic-calibration', labelKey: 'nav.epistemic-calibration', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'socratic-pivot', labelKey: 'nav.socratic-pivot', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'concession-engine', labelKey: 'nav.concession-engine', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'bayesian-judges', labelKey: 'nav.bayesian-judges', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'dpo-sampler', labelKey: 'nav.dpo-sampler', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'critic', labelKey: 'nav.critic', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'pivot', labelKey: 'nav.pivot', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'concession', labelKey: 'nav.concession', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'triangulation', labelKey: 'nav.triangulation', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'empathy', labelKey: 'nav.empathy', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'heat', labelKey: 'nav.heat', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'sentinel', labelKey: 'nav.sentinel', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'redundancy', labelKey: 'nav.redundancy', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'replay', labelKey: 'nav.replay', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'enthymeme', labelKey: 'nav.enthymeme', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'multi-hop', labelKey: 'nav.multi-hop', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'bias-exploit', labelKey: 'nav.bias-exploit', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'interrupt', labelKey: 'nav.interrupt', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'frame', labelKey: 'nav.frame', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'rhetorical-device', labelKey: 'nav.rhetorical-device', icon: React.createElement(Sparkles), color: '#0ea5e9', lazy: true },
    { id: 'narrative-arc', labelKey: 'nav.narrative-arc', icon: React.createElement(Sparkles), color: '#0ea5e9', lazy: true },
    { id: 'abstraction-ladder', labelKey: 'nav.abstraction-ladder', icon: React.createElement(Sparkles), color: '#0ea5e9', lazy: true },
    { id: 'role-reversal', labelKey: 'nav.role-reversal', icon: React.createElement(Sparkles), color: '#0ea5e9', lazy: true },
    { id: 'fog-of-war', labelKey: 'nav.fog-of-war', icon: React.createElement(Sparkles), color: '#0ea5e9', lazy: true },
    { id: 'evidence-revelation', labelKey: 'nav.evidence-revelation', icon: React.createElement(Sparkles), color: '#0ea5e9', lazy: true },
    { id: 'humor', labelKey: 'nav.humor', icon: React.createElement(Sparkles), color: '#0ea5e9', lazy: true },
    { id: 'status-dynamics', labelKey: 'nav.status-dynamics', icon: React.createElement(Sparkles), color: '#0ea5e9', lazy: true },
    { id: 'style-matching', labelKey: 'nav.style-matching', icon: React.createElement(Sparkles), color: '#0ea5e9', lazy: true },
    { id: 'dynamic-persona', labelKey: 'nav.dynamic-persona', icon: React.createElement(Sparkles), color: '#0ea5e9', lazy: true },
    { id: 'strategist', labelKey: 'nav.strategist', icon: React.createElement(Sparkles), color: '#0ea5e9', lazy: true },
    { id: 'whisper-channels', labelKey: 'nav.whisper-channels', icon: React.createElement(Sparkles), color: '#0ea5e9', lazy: true },
    { id: 'alliance', labelKey: 'nav.alliance', icon: React.createElement(Sparkles), color: '#0ea5e9', lazy: true },
    { id: 'prediction-market', labelKey: 'nav.prediction-market', icon: React.createElement(Sparkles), color: '#0ea5e9', lazy: true },
    { id: 'rtom', labelKey: 'nav.rtom', icon: React.createElement(Sparkles), color: '#0ea5e9', lazy: true },
    { id: 'strategy-fingerprint', labelKey: 'nav.strategy-fingerprint', icon: React.createElement(Sparkles), color: '#0ea5e9', lazy: true },
    { id: 'objection-anticipation', labelKey: 'nav.objection-anticipation', icon: React.createElement(Shield), color: '#8b5cf6', lazy: true },
    { id: 'evidence-triangulation', labelKey: 'nav.evidence-triangulation', icon: React.createElement(Shield), color: '#8b5cf6', lazy: true },
    { id: 'hegelian-synthesis', labelKey: 'nav.hegelian-synthesis', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'uncertainty-propagation', labelKey: 'nav.uncertainty-propagation', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'rhetoric-safety', labelKey: 'nav.rhetoric-safety', icon: React.createElement(Sparkles), color: '#0ea5e9', lazy: true },
    { id: 'blind-evaluation', labelKey: 'nav.blind-evaluation', icon: React.createElement(Sparkles), color: '#0ea5e9', lazy: true },
    { id: 'bidding-time', labelKey: 'nav.bidding-time', icon: React.createElement(Sparkles), color: '#0ea5e9', lazy: true },
    { id: 'adaptive-order', labelKey: 'nav.adaptive-order', icon: React.createElement(Sparkles), color: '#0ea5e9', lazy: true },
    { id: 'executable-evidence', labelKey: 'nav.executable-evidence', icon: React.createElement(Shield), color: '#8b5cf6', lazy: true },
    { id: 'hidden-incentives', labelKey: 'nav.hidden-incentives', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'semantic-blending', labelKey: 'nav.semantic-blending', icon: React.createElement(Zap), color: '#6366f1', lazy: true },
    { id: 'judge-deliberation', labelKey: 'nav.judge-deliberation', icon: React.createElement(Sparkles), color: '#0ea5e9', lazy: true },
];
