import { Icons } from './route-registry-icons';
import type { NavSection } from './types/routing';

export const SYSTEM_SECTIONS: NavSection[] = [
    {
        id: 'section-agents',
        labelKey: 'nav.section_agents',
        items: [
            {
                id: 'agents',
                labelKey: 'nav.agents',
                icon: Icons.bot,
                color: '#8b5cf6',
            },
            {
                id: 'roles',
                labelKey: 'nav.roles',
                icon: Icons.users,
                color: '#3b82f6',
            },
            {
                id: 'roles-consortia',
                labelKey: 'nav.roles_consortia',
                icon: Icons.users,
                color: '#8b5cf6',
                lazy: true,
            },
            {
                id: 'sre',
                labelKey: 'nav.sre_agent',
                icon: Icons.zap,
                color: '#ef4444',
                lazy: true,
            },
            {
                id: 'agent-journal',
                labelKey: 'nav.agent_journal',
                icon: Icons.bookOpen,
                color: '#8b5cf6',
                lazy: true,
            },
            {
                id: 'mission',
                labelKey: 'nav.mission_control',
                icon: Icons.zap,
                color: '#f59e0b',
                lazy: true,
            },
            {
                id: 'live',
                labelKey: 'nav.live_workspace',
                icon: Icons.radio,
                color: '#3b82f6',
                lazy: true,
            },
            {
                id: 'agent-marketplace',
                labelKey: 'nav.agent_marketplace',
                icon: Icons.star,
                color: '#a855f7',
                lazy: true,
            },
            {
                id: 'agent-comparison',
                labelKey: 'nav.agent_comparison',
                icon: Icons.gitCompare,
                color: '#a855f7',
                lazy: true,
            },
            {
                id: 'agent-protocol',
                labelKey: 'nav.agent_protocol',
                icon: Icons.network,
                color: '#8b5cf6',
                lazy: true,
            },
            {
                id: 'persona-marketplace',
                labelKey: 'nav.persona_marketplace',
                icon: Icons.store,
                color: '#a855f7',
                lazy: true,
            },
            {
                id: 'persona-picker',
                labelKey: 'nav.persona_picker',
                icon: Icons.sparkles,
                color: '#8b5cf6',
                lazy: true,
            },
            // Agent parts moved here from INTEGRATIONS/CONNECTIONS (menu cleanup).
            // Route ids unchanged, only grouping changed.
            {
                id: 'skills',
                labelKey: 'nav.skills',
                icon: Icons.gitMerge,
                color: '#f59e0b',
            },
            {
                id: 'tools',
                labelKey: 'nav.tools',
                icon: Icons.wrench,
                color: '#f59e0b',
            },
            {
                id: 'connectors',
                labelKey: 'nav.connectors',
                icon: Icons.share2,
                color: '#3b82f6',
            },
            {
                id: 'mcp',
                labelKey: 'nav.mcp_servers',
                icon: Icons.server,
                color: '#a855f7',
            },
        ],
    },
    {
        id: 'section-diagnostics',
        labelKey: 'nav.section_diagnostics',
        items: [
            {
                id: 'logs',
                labelKey: 'nav.log_browser',
                icon: Icons.terminal,
                color: '#94a3b8',
                lazy: true,
            },
            {
                id: 'debugger',
                labelKey: 'nav.traces',
                icon: Icons.gitBranch,
                color: '#a855f7',
                lazy: true,
            },
            {
                id: 'router-trace',
                labelKey: 'nav.router_trace',
                icon: Icons.network,
                color: '#8b5cf6',
                lazy: true,
            },
            {
                id: 'memory',
                labelKey: 'nav.memory',
                icon: Icons.database,
                color: '#a855f7',
                lazy: true,
            },
            {
                id: 'memory-palace',
                labelKey: 'nav.memory_palace',
                icon: Icons.database,
                color: '#8b5cf6',
                lazy: true,
                experimental: true,
            },
            {
                id: 'health',
                labelKey: 'nav.health',
                icon: Icons.heart,
                color: '#ef4444',
                lazy: true,
            },
            {
                id: 'system-health',
                labelKey: 'nav.system_health',
                icon: Icons.activity,
                color: '#22c55e',
                lazy: true,
            },
            {
                id: 'docs-health',
                labelKey: 'nav.docs_health',
                icon: Icons.fileCode,
                color: '#22c55e',
                lazy: true,
            },
            {
                id: 'pressure',
                labelKey: 'nav.pressure_map',
                icon: Icons.thermometer,
                color: '#f97316',
                lazy: true,
            },
            {
                id: 'runtime-pressure',
                labelKey: 'nav.runtime_pressure_map',
                icon: Icons.activity,
                color: '#f97316',
                lazy: true,
            },
            {
                id: 'what-if',
                labelKey: 'nav.what_if',
                icon: Icons.shuffle,
                color: '#8b5cf6',
                lazy: true,
                experimental: true,
            },
            {
                id: 'dependency-map',
                labelKey: 'nav.dependency_graph',
                icon: Icons.gitCompare,
                color: '#3b82f6',
                lazy: true,
            },
            {
                id: 'diagnostics',
                labelKey: 'nav.diagnostics',
                icon: Icons.crosshair,
                color: '#10b981',
                lazy: true,
            },
            {
                id: 'state-inspector',
                labelKey: 'nav.state_inspector',
                icon: Icons.eye,
                color: '#3b82f6',
                lazy: true,
            },
            {
                id: 'performance-profiler',
                labelKey: 'nav.performance_profiler',
                icon: Icons.trendingUp,
                color: '#a855f7',
                lazy: true,
            },
            {
                id: 'shadow',
                labelKey: 'nav.shadow',
                icon: Icons.gitBranch,
                color: '#8b5cf6',
                lazy: true,
                experimental: true,
            },
            {
                id: 'causal-debugger',
                labelKey: 'nav.causal_debugger',
                icon: Icons.shuffle,
                color: '#a78bfa',
                lazy: true,
                experimental: true,
            },
            {
                id: 'counterfactual',
                labelKey: 'nav.counterfactual',
                icon: Icons.messageCircle,
                color: '#f59e0b',
                lazy: true,
                experimental: true,
            },
        ],
    },
];
