import { Icons } from './route-registry-icons';
import type { NavSection } from './types/routing';

export const CONTENT_SECTIONS: NavSection[] = [
    // KNOWLEDGE split into one section per item (menu cleanup).
    // Route ids unchanged, only grouping changed.
    {
        id: 'section-knowledge-one',
        labelKey: 'nav.section_knowledge_one',
        items: [
            {
                id: 'knowledge',
                labelKey: 'nav.knowledge',
                icon: Icons.brain,
                color: '#a855f7',
            },
        ],
    },
    {
        id: 'section-project-os',
        labelKey: 'nav.section_project_os',
        items: [
            {
                id: 'project-os',
                labelKey: 'nav.project_os_explorer',
                icon: Icons.search,
                color: '#8b5cf6',
                lazy: true,
                experimental: true,
            },
        ],
    },
    {
        id: 'section-lenses',
        labelKey: 'nav.section_lenses',
        items: [
            {
                id: 'lenses',
                labelKey: 'nav.lenses',
                icon: Icons.layers,
                color: '#8b5cf6',
                lazy: true,
                experimental: true,
            },
        ],
    },
    {
        id: 'section-crystals',
        labelKey: 'nav.section_crystals',
        items: [
            {
                id: 'crystals',
                labelKey: 'nav.crystals',
                icon: Icons.gem,
                color: '#10b981',
                lazy: true,
                experimental: true,
            },
        ],
    },
    {
        id: 'section-junctions',
        labelKey: 'nav.section_junctions',
        items: [
            {
                id: 'junctions',
                labelKey: 'nav.junctions',
                icon: Icons.waypoints,
                color: '#8b5cf6',
                lazy: true,
                experimental: true,
            },
        ],
    },
    {
        id: 'section-synthesis',
        labelKey: 'nav.section_synthesis',
        items: [
            {
                id: 'synthesis',
                labelKey: 'nav.synthesis',
                icon: Icons.combine,
                color: '#f59e0b',
                lazy: true,
                experimental: true,
            },
        ],
    },
    {
        id: 'section-knowledge-generator',
        labelKey: 'nav.section_knowledge_generator',
        items: [
            {
                id: 'knowledge-generator',
                labelKey: 'nav.knowledge_generator',
                icon: Icons.lightbulb,
                color: '#22c55e',
                lazy: true,
                experimental: true,
            },
        ],
    },
    {
        id: 'section-forum',
        labelKey: 'nav.section_forum',
        items: [
            {
                id: 'forum',
                labelKey: 'nav.forum',
                icon: Icons.messagesSquare,
                color: '#8b5cf6',
                lazy: true,
                experimental: true,
            },
        ],
    },
    {
        id: 'section-builder',
        labelKey: 'nav.section_builder',
        items: [
            {
                id: 'builder',
                labelKey: 'nav.builder',
                icon: Icons.wrench,
                color: '#f97316',
                lazy: true,
                experimental: true,
            },
        ],
    },
    {
        id: 'section-director',
        labelKey: 'nav.section_director',
        items: [
            {
                id: 'director',
                labelKey: 'nav.director',
                icon: Icons.director,
                color: '#06b6d4',
                lazy: true,
                experimental: true,
            },
        ],
    },
    {
        id: 'section-room',
        labelKey: 'nav.section_room',
        items: [
            {
                id: 'room',
                labelKey: 'nav.room',
                icon: Icons.room,
                color: '#22d3ee',
                lazy: true,
                experimental: true,
            },
        ],
    },
    {
        id: 'section-projects',
        labelKey: 'nav.section_projects',
        items: [
            {
                id: 'projects',
                labelKey: 'nav.projects',
                icon: Icons.folderOpen,
                color: '#3b82f6',
                lazy: true,
                experimental: true,
            },
        ],
    },
    {
        // FLEET + GOVERNANCE category (menu cleanup). Route ids unchanged, only grouping changed.
        id: 'section-fleet',
        labelKey: 'nav.section_fleet',
        items: [
            {
                id: 'fleet',
                labelKey: 'nav.fleet',
                icon: Icons.waypoints,
                color: '#f59e0b',
                lazy: true,
                experimental: true,
            },
            {
                id: 'fleet-crews',
                labelKey: 'nav.fleet_crews',
                icon: Icons.users,
                color: '#10b981',
                lazy: true,
            },
            {
                id: 'fleet-councils',
                labelKey: 'nav.fleet_councils',
                icon: Icons.gitCompare,
                color: '#a855f7',
                lazy: true,
            },
            {
                id: 'fleet-graphs',
                labelKey: 'nav.fleet_graphs',
                icon: Icons.route,
                color: '#3b82f6',
                lazy: true,
            },
            {
                id: 'fleet-persona',
                labelKey: 'nav.fleet_persona',
                icon: Icons.users,
                color: '#ec4899',
                lazy: true,
            },
            {
                id: 'fleet-interop',
                labelKey: 'nav.fleet_interop',
                icon: Icons.network,
                color: '#06b6d4',
                lazy: true,
            },
            {
                id: 'fleet-frontier',
                labelKey: 'nav.fleet_frontier',
                icon: Icons.rocket,
                color: '#f97316',
                lazy: true,
            },
            {
                id: 'simulation',
                labelKey: 'nav.simulation',
                icon: Icons.flaskConical,
                color: '#06b6d4',
                lazy: true,
            },
            {
                id: 'provenance',
                labelKey: 'nav.provenance',
                icon: Icons.gitBranch,
                color: '#8b5cf6',
                lazy: true,
            },
            {
                id: 'gov-stress-test',
                labelKey: 'nav.governance_stress_test',
                icon: Icons.shield,
                color: '#ef4444',
                lazy: true,
                experimental: true,
            },
            {
                id: 'obs-gaps',
                labelKey: 'nav.observability_gaps_scanner',
                icon: Icons.crosshair,
                color: '#f97316',
                lazy: true,
                experimental: true,
            },
        ],
    },
    {
        // GoogleAI category — all Google/Gemini panels in one place (menu cleanup).
        // Route ids unchanged, only grouping changed.
        id: 'section-google',
        labelKey: 'nav.section_google',
        items: [
            {
                id: 'google-studio',
                labelKey: 'nav.google_studio',
                icon: Icons.shield,
                color: '#4285F4',
                lazy: true,
            },
            {
                id: 'google-cache',
                labelKey: 'nav.google_cache',
                icon: Icons.container,
                color: '#4285F4',
                lazy: true,
            },
            {
                id: 'gemini-live',
                labelKey: 'nav.gemini_live',
                icon: Icons.mic,
                color: '#4285F4',
                lazy: true,
                experimental: true,
            },
            {
                id: 'research-gemini',
                labelKey: 'nav.research_gemini',
                icon: Icons.sparkles,
                color: '#8b5cf6',
                lazy: true,
                experimental: true,
            },
        ],
    },
    {
        // DOCUMENTATION category (menu cleanup). Route ids unchanged.
        id: 'section-docs',
        labelKey: 'nav.section_docs',
        items: [
            {
                id: 'docs',
                labelKey: 'nav.docs',
                icon: Icons.bookText,
                color: '#8b5cf6',
            },
            {
                id: 'decision-log',
                labelKey: 'nav.decision_log',
                icon: Icons.clipboardList,
                color: '#10b981',
                lazy: true,
            },
            {
                id: 'arch-review',
                labelKey: 'nav.architecture_review',
                icon: Icons.bookText,
                color: '#10b981',
                lazy: true,
                experimental: true,
            },
            {
                id: 'prompt-audit',
                labelKey: 'nav.prompt_strategy_audit',
                icon: Icons.terminal,
                color: '#f59e0b',
                lazy: true,
                experimental: true,
            },
            {
                id: 'template-sharing',
                labelKey: 'nav.template_sharing',
                icon: Icons.share2,
                color: '#10b981',
                lazy: true,
            },
        ],
    },
    {
        // RESEARCH category (menu cleanup). Route ids unchanged, only grouping changed.
        id: 'section-research',
        labelKey: 'nav.section_research',
        items: [
            {
                id: 'research-engine',
                labelKey: 'nav.research_engine',
                icon: Icons.layers,
                color: '#8b5cf6',
                lazy: true,
                experimental: true,
            },
            {
                id: 'debate-system-research',
                labelKey: 'nav.debate_system_research',
                icon: Icons.flaskConical,
                color: '#a855f7',
                lazy: true,
                experimental: true,
            },
            {
                id: 'research-reports',
                labelKey: 'nav.research_reports',
                icon: Icons.bookOpen,
                color: '#a855f7',
                lazy: true,
                experimental: true,
            },
            {
                id: 'research-advanced',
                labelKey: 'nav.research_advanced',
                icon: Icons.layers,
                color: '#8b5cf6',
                lazy: true,
                experimental: true,
            },
            {
                id: 'hypothesis-gen',
                labelKey: 'nav.hypothesis_generator',
                icon: Icons.flaskConical,
                color: '#3b82f6',
                lazy: true,
                experimental: true,
            },
            {
                id: 'eval-datasets',
                labelKey: 'nav.eval_datasets',
                icon: Icons.barChart3,
                color: '#a855f7',
                lazy: true,
            },
            {
                id: 'routing-experiments',
                labelKey: 'nav.model_routing_experiments',
                icon: Icons.barChart3,
                color: '#8b5cf6',
                lazy: true,
                experimental: true,
            },
        ],
    },
    {
        id: 'section-integrations',
        labelKey: 'nav.section_integrations',
        items: [
            {
                id: 'editors',
                labelKey: 'nav.editors',
                icon: Icons.fileCode,
                color: '#06b6d4',
                lazy: true,
            },
            {
                id: 'cache',
                labelKey: 'nav.cache',
                icon: Icons.hardDrive,
                color: '#10b981',
                lazy: true,
            },
            {
                id: 'webhooks',
                labelKey: 'nav.webhooks',
                icon: Icons.webhook,
                color: '#a855f7',
                lazy: true,
            },
            {
                id: 'rotations',
                labelKey: 'nav.rotations',
                icon: Icons.refreshCw,
                color: '#3b82f6',
                lazy: true,
            },
            {
                id: 'service-registry',
                labelKey: 'nav.service_registry',
                icon: Icons.box,
                color: '#8b5cf6',
                lazy: true,
            },
            {
                id: 'topology-templates',
                labelKey: 'nav.topology_templates',
                icon: Icons.grid3X3,
                color: '#06b6d4',
                lazy: true,
            },
            {
                id: 'playground',
                labelKey: 'nav.playground',
                icon: Icons.flaskConical,
                color: '#a855f7',
                lazy: true,
                experimental: true,
            },
            {
                id: 'prompts',
                labelKey: 'nav.prompts',
                icon: Icons.fileText,
                color: '#06b6d4',
                lazy: true,
            },
            {
                id: 'prompt-versions',
                labelKey: 'nav.prompt_version_history',
                icon: Icons.history,
                color: '#8b5cf6',
                lazy: true,
            },
            {
                id: 'batch',
                labelKey: 'nav.batch_processing',
                icon: Icons.listOrdered,
                color: '#10b981',
                lazy: true,
            },
            {
                id: 'workflows',
                labelKey: 'nav.workflows',
                icon: Icons.gitPullRequest,
                color: '#3b82f6',
                lazy: true,
            },
            {
                id: 'security',
                labelKey: 'nav.security_scan',
                icon: Icons.shield,
                color: '#a855f7',
                lazy: true,
            },
            {
                id: 'ab-testing',
                labelKey: 'nav.ab_testing',
                icon: Icons.gitCompare,
                color: '#8b5cf6',
                lazy: true,
                experimental: true,
            },
            {
                id: 'fine-tuning',
                labelKey: 'nav.fine_tuning',
                icon: Icons.brain,
                color: '#a855f7',
                lazy: true,
            },
            {
                id: 'team-collaboration',
                labelKey: 'nav.team_collaboration',
                icon: Icons.users,
                color: '#a855f7',
                lazy: true,
            },
            {
                id: 'community-hub',
                labelKey: 'nav.community_hub',
                icon: Icons.share2,
                color: '#f59e0b',
                lazy: true,
            },
            {
                id: 'model-distillation',
                labelKey: 'nav.model_distillation',
                icon: Icons.brain,
                color: '#8b5cf6',
                lazy: true,
            },
            {
                id: 'deploy',
                labelKey: 'nav.deploy',
                icon: Icons.rocket,
                color: '#22c55e',
                lazy: true,
            },
            {
                id: 'voice-input',
                labelKey: 'nav.voice_input',
                icon: Icons.mic,
                color: '#3b82f6',
                lazy: true,
            },
            {
                id: 'plugin-sdk',
                labelKey: 'nav.plugin_sdk',
                icon: Icons.puzzle,
                color: '#a855f7',
                lazy: true,
            },
        ],
    },
    {
        id: 'section-settings',
        labelKey: 'nav.section_settings',
        items: [
            {
                id: 'settings',
                labelKey: 'nav.settings',
                icon: Icons.settings,
                color: '#64748b',
            },
            {
                id: 'policies',
                labelKey: 'nav.policies',
                icon: Icons.shield,
                color: '#10b981',
            },
            {
                id: 'policy-editor',
                labelKey: 'nav.policy_editor',
                icon: Icons.zap,
                color: '#06b6d4',
                lazy: true,
            },
            {
                id: 'audit',
                labelKey: 'nav.audit_log',
                icon: Icons.search,
                color: '#94a3b8',
            },
            {
                id: 'history',
                labelKey: 'nav.config_history',
                icon: Icons.history,
                color: '#f59e0b',
            },
            {
                id: 'export-import',
                labelKey: 'nav.export_import',
                icon: Icons.database,
                color: '#3b82f6',
                lazy: true,
            },
            {
                id: 'time-machine',
                labelKey: 'nav.time_machine',
                icon: Icons.clock,
                color: '#8b5cf6',
                lazy: true,
            },
        ],
    },
    {
        // RANDOMS — quarantine for unchecked items. Move here anything
        // that needs review before getting a real home (menu cleanup).
        id: 'section-randoms',
        labelKey: 'nav.section_randoms',
        items: [
            {
                id: 'bookmarks',
                labelKey: 'nav.bookmarks',
                icon: Icons.bookmark,
                color: '#f59e0b',
                lazy: true,
            },
            {
                id: 'aquarium',
                labelKey: 'nav.aquarium',
                icon: Icons.eye,
                color: '#06b6d4',
                lazy: true,
                experimental: true,
            },
            {
                id: 'ecosystem',
                labelKey: 'nav.ecosystem',
                icon: Icons.fish,
                color: '#22c55e',
                lazy: true,
                experimental: true,
            },
            {
                id: 'health-sla',
                labelKey: 'nav.health_sla',
                icon: Icons.slidersHorizontal,
                color: '#10b981',
                lazy: true,
            },
            {
                id: 'leaderboard',
                labelKey: 'nav.leaderboard',
                icon: Icons.trophy,
                color: '#f59e0b',
                lazy: true,
            },
            {
                id: 'federated-memory',
                labelKey: 'nav.federated_memory',
                icon: Icons.server,
                color: '#3b82f6',
                lazy: true,
                experimental: true,
            },
            {
                id: 'memory-export-import',
                labelKey: 'nav.memory_export_import',
                icon: Icons.upload,
                color: '#3b82f6',
                lazy: true,
            },
            {
                id: 'aquarium-trading',
                labelKey: 'nav.aquarium_trading',
                icon: Icons.fish,
                color: '#06b6d4',
                lazy: true,
                experimental: true,
            },
            {
                id: 'scheduler',
                labelKey: 'nav.scheduler',
                icon: Icons.clock,
                color: '#3b82f6',
                lazy: true,
                experimental: true,
            },
            {
                id: 'tutorials',
                labelKey: 'nav.tutorials',
                icon: Icons.sparkles,
                color: '#a855f7',
                lazy: true,
            },
            {
                id: 'meta-learning',
                labelKey: 'nav.meta_learning',
                icon: Icons.brain,
                color: '#a855f7',
                lazy: true,
                experimental: true,
            },
            {
                id: 'quantum-inspiration',
                labelKey: 'nav.quantum_inspiration',
                icon: Icons.atom,
                color: '#a855f7',
                lazy: true,
                experimental: true,
            },
            {
                id: 'governance',
                labelKey: 'nav.governance',
                icon: Icons.shield,
                color: '#ef4444',
                lazy: true,
            },
            {
                id: 'group-chat',
                labelKey: 'nav.group_chat',
                icon: Icons.users,
                color: '#3b82f6',
                lazy: true,
            },
            {
                id: 'guardrails',
                labelKey: 'nav.guardrails',
                icon: Icons.shield,
                color: '#ef4444',
                lazy: true,
            },
            {
                id: 'planner',
                labelKey: 'nav.planner',
                icon: Icons.clipboardList,
                color: '#f59e0b',
                lazy: true,
            },
            {
                id: 'autonomy',
                labelKey: 'nav.autonomy',
                icon: Icons.zap,
                color: '#10b981',
                lazy: true,
            },
            {
                id: 'dyad',
                labelKey: 'nav.dyad',
                icon: Icons.messageCircle,
                color: '#8b5cf6',
                lazy: true,
            },
            {
                id: 'sop',
                labelKey: 'nav.sop',
                icon: Icons.clipboardList,
                color: '#f59e0b',
                lazy: true,
            },
            {
                id: 'run-queue',
                labelKey: 'nav.run_queue',
                icon: Icons.listOrdered,
                color: '#3b82f6',
                lazy: true,
            },
            {
                id: 'rival-labs',
                labelKey: 'nav.rival_labs',
                icon: Icons.flaskConical,
                color: '#a855f7',
                lazy: true,
            },
            {
                id: 'rivals-catalog',
                labelKey: 'nav.rivals_catalog',
                icon: Icons.flaskConical,
                color: '#a855f7',
                lazy: true,
            },
            {
                id: 'patterns',
                labelKey: 'nav.patterns',
                icon: Icons.bookOpen,
                color: '#10b981',
            },
            {
                id: 'experimental',
                labelKey: 'nav.experimental',
                icon: Icons.flaskConical,
                color: '#a855f7',
                lazy: true,
                experimental: true,
            },
            {
                id: 'custom-metrics',
                labelKey: 'nav.custom_metrics',
                icon: Icons.barChart3,
                color: '#8b5cf6',
                lazy: true,
            },
            {
                id: 'key-usage-analytics',
                labelKey: 'nav.key_usage_analytics',
                icon: Icons.barChart3,
                color: '#8b5cf6',
                lazy: true,
            },
            {
                id: 'routing',
                labelKey: 'nav.routing_ai',
                icon: Icons.route,
                color: '#8b5cf6',
                lazy: true,
            },
            {
                id: 'contribution-graph',
                labelKey: 'nav.contribution_graph',
                icon: Icons.gitCommit,
                color: '#10b981',
                lazy: true,
            },
            {
                id: 'tasks',
                labelKey: 'nav.tasks',
                icon: Icons.checkSquare,
                color: '#f59e0b',
            },
            {
                id: 'files',
                labelKey: 'nav.files',
                icon: Icons.folderOpen,
                color: '#a855f7',
                lazy: true,
            },
        ],
    },
];
