import { makeHelpers } from './helpers';
import { registerPhase0 } from './phase0-event-bridge';
import { registerPhase1 } from './phase1-foundation';
import { registerPhase2 } from './phase2-infrastructure';
import { registerPhase3 } from './phase3-debate-runtime';
import { registerPhase4 } from './phase4-agents-roles';
import { registerPhase5 } from './phase5-routing-llm';
import { registerPhase6 } from './phase6-high-level';
import { registerPhase7 } from './phase7-memory-eval-metrics';
import { registerPhase8 } from './phase8-roles-consortia';
import { registerPhase9 } from './phase9-research-engine';
import { registerPhase10 } from './phase10-ecosystem';
import { registerPhase11 } from './phase11-causal-debugger';
import { registerPhase13 } from './phase13-lenses';
import { registerPhase14 } from './phase14-crystals';
import { registerPhase15 } from './phase15-junction';
import { registerPhase16 } from './phase16-synthesis';
import { registerPhase17 } from './phase17-knowledge-generator';
import { registerPhase18 } from './phase18-forum';
import { registerPhase19 } from './phase19-builder';
import { registerPhase20 } from './phase20-director';
import { registerPhase21 } from './phase21-invocation';
import { registerPhase22 } from './phase22-cost-tracker';
import { registerPhase23 } from './phase23-crew';
import { registerPhase24 } from './phase24-council';
import { registerPhase25 } from './phase25-graph';
import { registerPhase26 } from './phase26-persona';
import { registerPhase27 } from './phase27-ops';
import { registerPhase28 } from './phase28-interop';
import { registerPhase29 } from './phase29-meta';
import { registerPhase30 } from './phase30-trust';
import { registerPhase31 } from './phase31-frontier';
import { registerPhase32 } from './phase32-parity';
import { registerPhase33 } from './phase33-rivals';
import { registerPhase34 } from './phase34-rivals2';
import { registerPhase35 } from './phase35-rivals3';
import { registerPhase36 } from './phase36-rivals4';
import { registerPhase37 } from './phase37-rivals5';
import { registerPhase38 } from './phase38-rivals6';
import { registerPhase39 } from './phase39-debateplus';
import { registerPhase40 } from './phase40-rivals7';
import { registerPhase41 } from './phase41-rivals9';
import { registerPhase42 } from './phase42-rivals10';
import { registerPhase43 } from './phase43-rivals11';
import { registerPhase44 } from './phase44-rivals12';
import { registerPhase45 } from './phase45-business';
import { registerPhase46 } from './phase46-anthropic';
import { registerPhase47 } from './phase47-russian';
import { registerPhase48 } from './phase48-synth';
import { registerPhase49 } from './phase49-synth2';
import { registerPhase50 } from './phase50-synth3';
import { registerPhase51 } from './phase51-coding2';
import { registerPhase52 } from './phase52-coding3';
import { registerPhase53 } from './phase53-capability';
import { registerPhase54 } from './phase54-hybrid-rag';
import { registerPhase55 } from './phase55-tool-catalog';
import { registerPhase56 } from './phase56-execution-viz';
import { registerPhase57 } from './phase57-deploy-bundle';
import { registerPhase58 } from './phase58-code-sandbox';
import { registerPhase59 } from './phase59-browser-harness';
import { registerPhase60 } from './phase60-mcp-harness';
import { registerPhase61 } from './phase61-eval-scorers';
import { registerPhase62 } from './phase62-world-state';
import { registerPhase63 } from './phase63-simulation-engine';
import { registerPhase64 } from './phase64-agent-adapter';
import { registerPhase65 } from './phase65-council-migration';
import { registerPhase66 } from './phase66-projects';
import { registerPhase67 } from './phase67-channels';
import type { IContainer } from '../container';
import type { IEventBus } from '../types/interfaces';

export function registerServices(
    container: IContainer,
    eventBus: IEventBus,
    registerWithLifecycle: (name: string, instance: unknown) => void,
): void {
    const ctx = { container, eventBus, registerWithLifecycle };
    const helpers = makeHelpers(ctx);

    registerPhase0(helpers, ctx);
    registerPhase1(helpers, ctx);
    registerPhase2(helpers, ctx);
    registerPhase3(helpers, ctx);
    registerPhase4(helpers, ctx);
    registerPhase5(helpers, ctx);
    registerPhase6(helpers, ctx);
    registerPhase7(helpers, ctx);
    registerPhase8(helpers, ctx);
    registerPhase9(helpers, ctx);
    registerPhase10(helpers, ctx);
    registerPhase11(helpers, ctx);
    registerPhase13(helpers, ctx);
    registerPhase14(helpers, ctx);
    registerPhase15(helpers, ctx);
    registerPhase16(helpers, ctx);
    registerPhase17(helpers, ctx);
    registerPhase18(helpers, ctx);
    registerPhase19(helpers, ctx);
    registerPhase20(helpers, ctx);
    registerPhase21(helpers, ctx);
    registerPhase22(helpers, ctx);
    registerPhase23(helpers, ctx);
    registerPhase24(helpers, ctx);
    registerPhase25(helpers, ctx);
    registerPhase26(helpers, ctx);
    registerPhase27(helpers, ctx);
    registerPhase28(helpers, ctx);
    registerPhase29(helpers, ctx);
    registerPhase30(helpers, ctx);
    registerPhase31(helpers, ctx);
    registerPhase32(helpers, ctx);
    registerPhase33(helpers, ctx);
    registerPhase34(helpers, ctx);
    registerPhase35(helpers, ctx);
    registerPhase36(helpers, ctx);
    registerPhase37(helpers, ctx);
    registerPhase38(helpers, ctx);
    registerPhase39(helpers, ctx);
    registerPhase40(helpers, ctx);
    registerPhase41(helpers, ctx);
    registerPhase42(helpers, ctx);
    registerPhase43(helpers, ctx);
    registerPhase44(helpers, ctx);
    registerPhase45(helpers, ctx);
    registerPhase46(helpers, ctx);
    registerPhase47(helpers, ctx);
    registerPhase48(helpers, ctx);
    registerPhase49(helpers, ctx);
    registerPhase50(helpers, ctx);
    registerPhase51(helpers, ctx);
    registerPhase52(helpers, ctx);
    registerPhase53(helpers, ctx);
    registerPhase54(helpers, ctx);
    registerPhase55(helpers, ctx);
    registerPhase56(helpers, ctx);
    registerPhase57(helpers, ctx);
    registerPhase58(helpers, ctx);
    registerPhase59(helpers, ctx);
    registerPhase60(helpers, ctx);
    registerPhase61(helpers, ctx);
    registerPhase62(helpers, ctx);
    registerPhase63(helpers, ctx);
    registerPhase64(helpers, ctx);
    registerPhase65(helpers, ctx);
    registerPhase66(helpers, ctx);
    registerPhase67(helpers, ctx);
}

export type { PhaseContext, Phase } from './helpers';
