import {
    Lightbulb,
    AlertTriangle,
    BarChart3,
    Code,
    Shield,
    Users,
    Search,
    FileText,
    BookOpen,
    Calendar,
    Star,
    MessageSquare,
    Rocket,
    Layers,
    Calculator,
    Atom,
    FlaskConical,
    Leaf,
    Monitor,
    DollarSign,
    Globe,
    Brain,
    Heart,
    Scale,
    Stethoscope,
    TreePine,
    TrendingUp,
    Lock,
    Cpu,
    HeadphonesIcon,
    Sparkles,
    Layout,
    Network,
    Bug,
    Database,
    Zap,
    FlaskConical,
    BarChart,
    Palette,
    PenTool,
    MousePointer,
    FolderKanban,
    Target,
    UserCog,
    BookMarked,
    FileSearch,
    FileDown,
    History,
    ClipboardCheck,
} from 'lucide-react';
import type { UiAgentTemplate } from './AgentsPanelContext';

export const AGENT_TEMPLATES: UiAgentTemplate[] = [
    // ═══ Original English agents (25) ═══
    {
        id: 'agent-network',
        name: 'Network Engineer',
        description: 'Designs and optimizes network infrastructure, TCP/IP, SDN, latency.',
        icon: <Network size={20} />,
        color: '#06b6d4',
        config: {
            roleName: 'Network Engineer',
            prompt: 'You are a network engineer. Design and optimize network infrastructure, TCP/IP, SDN, and latency.',
            tools: ['web_search'],
            temperature: 0.3,
        },
    },
    {
        id: 'agent-risk',
        name: 'Risk Analyst',
        description: 'Identifies and quantifies risks, Monte Carlo simulation, compliance.',
        icon: <Bug size={20} />,
        color: '#ef4444',
        config: {
            roleName: 'Risk Analyst',
            prompt: 'You are a risk analyst. Identify and quantify risks, run Monte Carlo simulations, ensure compliance.',
            tools: ['data_analysis'],
            temperature: 0.3,
        },
    },
    {
        id: 'agent-ethics',
        name: 'Ethics Officer',
        description: 'Evaluates decisions for fairness, transparency, accountability, and bias.',
        icon: <Shield size={20} />,
        color: '#a855f7',
        config: {
            roleName: 'Ethics Officer',
            prompt: 'You are an ethics officer. Evaluate decisions for fairness, transparency, accountability, and bias.',
            tools: [],
            temperature: 0.2,
        },
    },
    {
        id: 'agent-architect',
        name: 'System Architect',
        description: 'Designs distributed systems, event-driven architecture, scalability.',
        icon: <Layout size={20} />,
        color: '#8b5cf6',
        config: {
            roleName: 'System Architect',
            prompt: 'You are a system architect. Design distributed systems, event-driven architecture, and scalable solutions.',
            tools: ['code_generation', 'code_review'],
            temperature: 0.2,
        },
    },
    {
        id: 'agent-security',
        name: 'Security Engineer',
        description: 'Identifies threats, attack vectors, defense-in-depth, STRIDE, OWASP.',
        icon: <Lock size={20} />,
        color: '#10b981',
        config: {
            roleName: 'Security Engineer',
            prompt: 'You are a security engineer. Identify threats, attack vectors, and security gaps. Apply defense-in-depth and least-privilege.',
            tools: ['vulnerability_scan', 'code_audit'],
            temperature: 0.15,
        },
    },
    {
        id: 'agent-devops',
        name: 'DevOps Engineer',
        description: 'CI/CD pipelines, infrastructure-as-code, deployment, observability.',
        icon: <Cpu size={20} />,
        color: '#f59e0b',
        config: {
            roleName: 'DevOps Engineer',
            prompt: 'You are a DevOps engineer. Design CI/CD pipelines, infrastructure-as-code, and deployment strategies.',
            tools: ['code_interpreter', 'code_review'],
            temperature: 0.2,
        },
    },
    {
        id: 'agent-database',
        name: 'Database Engineer',
        description: 'Schema design, query optimization, migrations, indexing, sharding.',
        icon: <Database size={20} />,
        color: '#06b6d4',
        config: {
            roleName: 'Database Engineer',
            prompt: 'You are a database engineer. Design schemas, optimize queries, plan migrations. Consider indexing, sharding, replication.',
            tools: ['data_analysis'],
            temperature: 0.2,
        },
    },
    {
        id: 'agent-perf',
        name: 'Performance Engineer',
        description: 'Identifies bottlenecks, measures throughput and latency, optimizations.',
        icon: <Zap size={20} />,
        color: '#f97316',
        config: {
            roleName: 'Performance Engineer',
            prompt: 'You are a performance engineer. Identify bottlenecks, measure throughput and latency. Propose concrete optimizations.',
            tools: ['code_interpreter'],
            temperature: 0.25,
        },
    },
    {
        id: 'agent-critic',
        name: 'Critical Auditor',
        description: 'Finds weaknesses, edge cases, logical fallacies, improvement suggestions.',
        icon: <Search size={20} />,
        color: '#ec4899',
        config: {
            roleName: 'Critical Auditor',
            prompt: 'You are a critical auditor. Find weaknesses, edge cases, and logical fallacies. Provide concrete improvement suggestions.',
            tools: ['vulnerability_scan', 'code_audit'],
            temperature: 0.1,
        },
    },
    {
        id: 'agent-data',
        name: 'Data Scientist',
        description: 'Statistical reasoning, empirical evidence, correlation vs causation.',
        icon: <BarChart size={20} />,
        color: '#14b8a6',
        config: {
            roleName: 'Data Scientist',
            prompt: 'You are a data scientist. Base analysis on statistical reasoning and empirical evidence. Distinguish correlation from causation.',
            tools: ['data_analysis', 'visualization'],
            temperature: 0.3,
        },
    },
    {
        id: 'agent-research',
        name: 'Research Analyst',
        description: 'Deep research, web search, document analysis, synthesis.',
        icon: <BookOpen size={20} />,
        color: '#6366f1',
        config: {
            roleName: 'Research Analyst',
            prompt: 'You are a research analyst. Conduct deep research, search the web, analyze documents, and provide comprehensive summaries.',
            tools: ['web_search', 'summarize'],
            temperature: 0.3,
        },
    },
    {
        id: 'agent-quality',
        name: 'Quality Engineer',
        description: 'Testing strategies, coverage gaps, quality gates, test automation.',
        icon: <ClipboardCheck size={20} />,
        color: '#10b981',
        config: {
            roleName: 'Quality Engineer',
            prompt: 'You are a quality engineer. Design testing strategies, identify coverage gaps, enforce quality gates.',
            tools: ['code_interpreter', 'code_review'],
            temperature: 0.2,
        },
    },
    {
        id: 'agent-creative',
        name: 'Creative Visionary',
        description: 'Generates novel ideas, thinks outside the box, lateral thinking.',
        icon: <Sparkles size={20} />,
        color: '#a855f7',
        config: {
            roleName: 'Creative Visionary',
            prompt: 'You are a creative visionary. Generate novel ideas, think outside the box, explore unconventional approaches.',
            tools: [],
            temperature: 0.8,
        },
    },
    {
        id: 'agent-designer',
        name: 'Product Designer',
        description: 'User-centered design, interaction patterns, visual hierarchy.',
        icon: <Palette size={20} />,
        color: '#ec4899',
        config: {
            roleName: 'Product Designer',
            prompt: 'You are a product designer. Focus on user-centered design, interaction patterns, and visual hierarchy.',
            tools: [],
            temperature: 0.5,
        },
    },
    {
        id: 'agent-content',
        name: 'Content Strategist',
        description: 'Crafts clear, engaging, audience-appropriate content.',
        icon: <PenTool size={20} />,
        color: '#f59e0b',
        config: {
            roleName: 'Content Strategist',
            prompt: 'You are a content strategist. Craft clear, engaging, and audience-appropriate content.',
            tools: ['web_search', 'summarize'],
            temperature: 0.6,
        },
    },
    {
        id: 'agent-ux',
        name: 'UX Researcher',
        description: 'Analyzes user behavior, identifies pain points, usability principles.',
        icon: <MousePointer size={20} />,
        color: '#06b6d4',
        config: {
            roleName: 'UX Researcher',
            prompt: 'You are a UX researcher. Analyze user behavior, identify pain points, propose evidence-based improvements.',
            tools: ['web_search'],
            temperature: 0.35,
        },
    },
    {
        id: 'agent-pm',
        name: 'Project Manager',
        description: 'Breaks down work into milestones, dependencies, resource needs.',
        icon: <FolderKanban size={20} />,
        color: '#3b82f6',
        config: {
            roleName: 'Project Manager',
            prompt: 'You are a project manager. Break down work into milestones, identify dependencies, assess resource needs.',
            tools: [],
            temperature: 0.3,
        },
    },
    {
        id: 'agent-po',
        name: 'Product Owner',
        description: 'Defines requirements, prioritizes backlog, scope trade-off decisions.',
        icon: <Target size={20} />,
        color: '#8b5cf6',
        config: {
            roleName: 'Product Owner',
            prompt: 'You are a product owner. Define requirements, prioritize the backlog by business value, make scope trade-off decisions.',
            tools: [],
            temperature: 0.3,
        },
    },
    {
        id: 'agent-lead',
        name: 'Team Lead',
        description: 'Guides development, mentors team, unblocks obstacles, code quality.',
        icon: <UserCog size={20} />,
        color: '#f59e0b',
        config: {
            roleName: 'Team Lead',
            prompt: 'You are a technical team lead. Guide development, mentor team members, unblock obstacles, ensure code quality.',
            tools: ['code_interpreter', 'code_review'],
            temperature: 0.25,
        },
    },
    {
        id: 'agent-writer',
        name: 'Technical Writer',
        description: 'Documents APIs, architecture decisions, user guides.',
        icon: <FileText size={20} />,
        color: '#14b8a6',
        config: {
            roleName: 'Technical Writer',
            prompt: 'You are a technical writer. Document APIs, architecture decisions, and user guides. Write clearly and precisely.',
            tools: ['web_search', 'summarize'],
            temperature: 0.3,
        },
    },
    {
        id: 'agent-doc-architect',
        name: 'Documentation Architect',
        description: 'Describes system structure precisely, maps code to architectural concepts.',
        icon: <BookMarked size={20} />,
        color: '#a855f7',
        config: {
            roleName: 'Documentation Architect',
            prompt: 'You are a documentation architect. Describe system structure precisely, mapping code components to architectural concepts.',
            tools: [],
            temperature: 0.1,
        },
    },
    {
        id: 'agent-doc-auditor',
        name: 'Documentation Auditor',
        description: 'Reviews documentation for compliance, accuracy, completeness.',
        icon: <FileSearch size={20} />,
        color: '#ec4899',
        config: {
            roleName: 'Documentation Auditor',
            prompt: 'You are a documentation auditor. Review documentation for compliance, accuracy, and completeness.',
            tools: [],
            temperature: 0.2,
        },
    },
    {
        id: 'agent-doc-simplifier',
        name: 'Documentation Simplifier',
        description: 'Makes complex descriptions accessible without changing meaning.',
        icon: <FileDown size={20} />,
        color: '#10b981',
        config: {
            roleName: 'Documentation Simplifier',
            prompt: 'You are a documentation simplifier. Make complex technical descriptions accessible without changing their meaning.',
            tools: [],
            temperature: 0.3,
        },
    },
    {
        id: 'agent-doc-historian',
        name: 'Documentation Historian',
        description: 'Provides narrative context for architectural decisions.',
        icon: <History size={20} />,
        color: '#6366f1',
        config: {
            roleName: 'Documentation Historian',
            prompt: 'You are a documentation historian. Provide narrative context for architectural decisions and explain why the system evolved.',
            tools: [],
            temperature: 0.4,
        },
    },
    {
        id: 'agent-doc-checker',
        name: 'Consistency Checker',
        description: 'Reports mismatches between documentation and code.',
        icon: <ClipboardCheck size={20} />,
        color: '#ef4444',
        config: {
            roleName: 'Consistency Checker',
            prompt: 'You are a consistency checker. Report mismatches between documentation and code. Compare every documented path against actual code.',
            tools: [],
            temperature: 0.1,
        },
    },

    // ═══ Russian Role System (27) ═══
    {
        id: 'agent-idea-generator',
        name: 'Генератор идей',
        description: 'Предлагает гипотезы, новые направления, варианты архитектуры и фичи.',
        icon: <Lightbulb size={20} />,
        color: '#f59e0b',
        config: {
            roleName: 'Генератор идей',
            prompt: 'Ты — Генератор идей. Предлагай гипотезы, новые направления, варианты архитектуры и функциональность. Мысли широко, предлагай нестандартные решения.',
            tools: [],
            temperature: 1.0,
        },
    },
    {
        id: 'agent-critic-ru',
        name: 'Критик',
        description: 'Ищет слабые места, противоречия, риски, ошибки в логике.',
        icon: <AlertTriangle size={20} />,
        color: '#ef4444',
        config: {
            roleName: 'Критик',
            prompt: 'Ты — Критик. Ищи слабые места, противоречия, риски, ошибки в логике и определениях.',
            tools: [],
            temperature: 0.2,
        },
    },
    {
        id: 'agent-analyst-ru',
        name: 'Аналитик',
        description: 'Разбирает ситуацию на части, сравнивает альтернативы, оценивает trade-offs.',
        icon: <BarChart3 size={20} />,
        color: '#3b82f6',
        config: {
            roleName: 'Аналитик',
            prompt: 'Ты — Аналитик. Разбирай ситуацию на части, сравнивай альтернативы, оценивай trade-offs.',
            tools: ['data_analysis'],
            temperature: 0.3,
        },
    },
    {
        id: 'agent-advocate',
        name: 'Защитник решения',
        description: 'Формулирует и отстаивает выбранное решение, отвечает на критику.',
        icon: <Shield size={20} />,
        color: '#8b5cf6',
        config: {
            roleName: 'Защитник решения (Адвокат)',
            prompt: 'Ты — Защитник решения (Адвокат). Формулируй и отстаивай выбранное решение, отвечай на критику.',
            tools: [],
            temperature: 0.5,
        },
    },
    {
        id: 'agent-moderator',
        name: 'Модератор',
        description: 'Держит структуру дискуссии, фиксирует тезисы, резюмирует.',
        icon: <Users size={20} />,
        color: '#06b6d4',
        config: {
            roleName: 'Модератор / Координатор',
            prompt: 'Ты — Модератор / Координатор. Держи структуру дискуссии, фиксируй тезисы, резюмируй.',
            tools: [],
            temperature: 0.4,
        },
    },
    {
        id: 'agent-fact-checker',
        name: 'Факт-чекер',
        description: 'Проверяет факты, документацию, совместимость, лицензии.',
        icon: <Search size={20} />,
        color: '#14b8a6',
        config: {
            roleName: 'Исследователь / Факт-чекер',
            prompt: 'Ты — Исследователь / Факт-чекер. Проверяй факты, документацию, совместимость, лицензии.',
            tools: ['web_search'],
            temperature: 0.1,
        },
    },
    {
        id: 'agent-secretary',
        name: 'Секретарь',
        description: 'Фиксирует решения, версии, чейнджлог, открытые вопросы.',
        icon: <FileText size={20} />,
        color: '#64748b',
        config: {
            roleName: 'Секретарь / Детерминатор',
            prompt: 'Ты — Секретарь / Детерминатор. Фиксируй решения, версии, чейнджлог, открытые вопросы.',
            tools: [],
            temperature: 0.2,
        },
    },
    {
        id: 'agent-erudit',
        name: 'Эрудит',
        description: 'Обеспечивает информацией, контекстом, ссылками на литературу.',
        icon: <BookOpen size={20} />,
        color: '#a855f7',
        config: {
            roleName: 'Эрудит',
            prompt: 'Ты — Эрудит. Обеспечивай группу информацией, контекстом, ссылками на литературу.',
            tools: ['web_search'],
            temperature: 0.5,
        },
    },
    {
        id: 'agent-organizer',
        name: 'Организатор',
        description: 'Разрабатывает программу работы, распределяет задачи, держит план.',
        icon: <Calendar size={20} />,
        color: '#f97316',
        config: {
            roleName: 'Организатор',
            prompt: 'Ты — Организатор. Разрабатывай программу работы, распределяй задачи, держи план и сроки.',
            tools: [],
            temperature: 0.3,
        },
    },
    {
        id: 'agent-expert',
        name: 'Эксперт',
        description: 'Оценивает каждый этап, определяет перспективы и годность.',
        icon: <Star size={20} />,
        color: '#eab308',
        config: {
            roleName: 'Эксперт',
            prompt: 'Ты — Эксперт. Оценивай каждый этап, определяй перспективы и «годность» промежуточных результатов.',
            tools: [],
            temperature: 0.4,
        },
    },
    {
        id: 'agent-communicator',
        name: 'Коммуникатор',
        description: 'Обеспечивает обмен информацией внутри группы и снаружи.',
        icon: <MessageSquare size={20} />,
        color: '#0ea5e9',
        config: {
            roleName: 'Коммуникатор',
            prompt: 'Ты — Коммуникатор. Обеспечивай обмен информацией внутри группы и связь с внешними источниками.',
            tools: [],
            temperature: 0.5,
        },
    },
    {
        id: 'agent-implementer',
        name: 'Реализатор',
        description: 'Доводит результаты до практической реализации, прототип, продукт.',
        icon: <Rocket size={20} />,
        color: '#dc2626',
        config: {
            roleName: 'Реализатор / Антрепренер',
            prompt: 'Ты — Реализатор / Антрепренер. Доводи результаты до практической реализации: прототип, продукт, внедрение.',
            tools: ['code_interpreter'],
            temperature: 0.4,
        },
    },
    {
        id: 'agent-arbiter',
        name: 'Систематизатор',
        description: 'Собирает и классифицирует предложения, ищет компромиссы.',
        icon: <Layers size={20} />,
        color: '#7c3aed',
        config: {
            roleName: 'Систематизатор / Арбитр',
            prompt: 'Ты — Систематизатор / Арбитр. Собирай и классифицируй предложения, ищи компромиссные альтернативы.',
            tools: [],
            temperature: 0.3,
        },
    },
    {
        id: 'agent-mathematician',
        name: 'Математик',
        description: 'Формализует задачи, строит модели, проверяет доказательства.',
        icon: <Calculator size={20} />,
        color: '#2563eb',
        config: {
            roleName: 'Математик',
            prompt: 'Ты — Математик. Формализуй задачи, строй модели, проверяй корректность выкладок и доказательств.',
            tools: ['code_interpreter'],
            temperature: 0.1,
        },
    },
    {
        id: 'agent-physicist',
        name: 'Физик',
        description: 'Оценивает физическую реализуемость, законы сохранения, энергобалансы.',
        icon: <Atom size={20} />,
        color: '#0891b2',
        config: {
            roleName: 'Физик',
            prompt: 'Ты — Физик. Оценивай физическую реализуемость, ограничения систем, законы сохранения.',
            tools: [],
            temperature: 0.2,
        },
    },
    {
        id: 'agent-chemist',
        name: 'Химик',
        description: 'Разбирает химические процессы, материалы, реакции, безопасность.',
        icon: <FlaskConical size={20} />,
        color: '#059669',
        config: {
            roleName: 'Химик',
            prompt: 'Ты — Химик. Разбирай химические процессы, материалы, реакции, совместимость веществ.',
            tools: [],
            temperature: 0.2,
        },
    },
    {
        id: 'agent-biologist',
        name: 'Биолог',
        description: 'Оценивает влияние на живые системы, экосистемы, эволюцию.',
        icon: <Leaf size={20} />,
        color: '#16a34a',
        config: {
            roleName: 'Биолог',
            prompt: 'Ты — Биолог. Оценивай влияние на живые системы, экосистемы, биосовместимость.',
            tools: [],
            temperature: 0.3,
        },
    },
    {
        id: 'agent-informatic',
        name: 'Информатик',
        description: 'Анализирует алгоритмы, сложность, архитектуру, масштабируемость.',
        icon: <Monitor size={20} />,
        color: '#6366f1',
        config: {
            roleName: 'Информатик / Компьютерный учёный',
            prompt: 'Ты — Информатик. Анализируй алгоритмы, сложность, архитектуру, масштабируемость ПО.',
            tools: ['code_interpreter'],
            temperature: 0.2,
        },
    },
    {
        id: 'agent-economist',
        name: 'Экономист',
        description: 'Считает затраты, выгоды, риски, модели рынка, бизнес-модели.',
        icon: <DollarSign size={20} />,
        color: '#ca8a04',
        config: {
            roleName: 'Экономист',
            prompt: 'Ты — Экономист. Считай затраты, выгоды, риски, модели рынка, устойчивость бизнес-моделей.',
            tools: ['data_analysis'],
            temperature: 0.3,
        },
    },
    {
        id: 'agent-statistician',
        name: 'Статистик',
        description: 'Проверяет данные, выборки, метрики, корректность выводов.',
        icon: <TrendingUp size={20} />,
        color: '#0284c7',
        config: {
            roleName: 'Статистик / Дата-сайентист',
            prompt: 'Ты — Статистик. Проверяй данные, выборки, метрики, корректность выводов, риски смещений.',
            tools: ['data_analysis'],
            temperature: 0.1,
        },
    },
    {
        id: 'agent-sociologist',
        name: 'Социолог',
        description: 'Смотрит на влияние на общество, группы, институты, социальные риски.',
        icon: <Globe size={20} />,
        color: '#7c3aed',
        config: {
            roleName: 'Социолог',
            prompt: 'Ты — Социолог. Смотрит на влияние на общество, группы, институты, социальные риски.',
            tools: [],
            temperature: 0.4,
        },
    },
    {
        id: 'agent-psychologist',
        name: 'Психолог',
        description: 'Оценивает влияние на поведение, мотивацию, когнитивные нагрузки.',
        icon: <Brain size={20} />,
        color: '#db2777',
        config: {
            roleName: 'Психолог',
            prompt: 'Ты — Психолог. Оценивай влияние на поведение, мотивацию, когнитивные нагрузки.',
            tools: [],
            temperature: 0.4,
        },
    },
    {
        id: 'agent-philosopher',
        name: 'Философ',
        description: 'Разбирает этические аспекты, ценностные конфликты, последствия.',
        icon: <Heart size={20} />,
        color: '#e11d48',
        config: {
            roleName: 'Философ / Этик',
            prompt: 'Ты — Философ / Этик. Разбирай этические аспекты, ценностные конфликты, долгосрочные последствия.',
            tools: [],
            temperature: 0.5,
        },
    },
    {
        id: 'agent-lawyer',
        name: 'Юрист',
        description: 'Проверяет соответствие законам, регуляциям, лицензиям, compliance.',
        icon: <Scale size={20} />,
        color: '#92400e',
        config: {
            roleName: 'Юрист / Правовед',
            prompt: 'Ты — Юрист / Правовед. Проверяй соответствие законам, регуляциям, лицензиям, compliance.',
            tools: [],
            temperature: 0.1,
        },
    },
    {
        id: 'agent-security-ru',
        name: 'Криптограф',
        description: 'Разбирает угрозы, атаки, защиту данных, криптографию.',
        icon: <Lock size={20} />,
        color: '#1e293b',
        config: {
            roleName: 'Специалист по безопасности / Криптограф',
            prompt: 'Ты — Криптограф. Разбирай угрозы, атаки, защиту данных, криптографические аспекты.',
            tools: ['vulnerability_scan'],
            temperature: 0.1,
        },
    },
    {
        id: 'agent-doctor',
        name: 'Врач',
        description: 'Оценивает влияние на здоровье, медицинские риски, клинические сценарии.',
        icon: <Stethoscope size={20} />,
        color: '#dc2626',
        config: {
            roleName: 'Врач / Биомедик',
            prompt: 'Ты — Врач / Биомедик. Оценивай влияние на здоровье, медицинские риски, клинические сценарии.',
            tools: [],
            temperature: 0.2,
        },
    },
    {
        id: 'agent-ecologist',
        name: 'Эколог',
        description: 'Смотрит на воздействие на окружающую среду, устойчивость, экориски.',
        icon: <TreePine size={20} />,
        color: '#15803d',
        config: {
            roleName: 'Эколог',
            prompt: 'Ты — Эколог. Смотрит на воздействие на окружающую среду, устойчивость, долгосрочные экологические риски.',
            tools: [],
            temperature: 0.3,
        },
    },
];
